const yellow = 'yellow';
const green = 'green';
const red = 'red';
const additional = 'additional';
export const colors = {
        b1: yellow,
        b2:red,
        d1: green,
        d2: yellow,
        d3: red,
        es: yellow,
        h: green,
        inh1: green,
        inh2: yellow,
        inh3: red,
        l: green,
        p1: green,
        p2: yellow,
        pk1: green,
        pk2: yellow,
        pk3: red,
        po: green,
        ppc1: yellow,
        ppc2:red,
        pr: red,
        ps1: yellow,
        ps2: red,
        pz1: green,
        pz2: red,
        s1: yellow,
        s2: red,
        sh: red,
        sn: yellow,
        v: red,
        wh: green,
        z1: yellow,
        z2: red,
        zl1: yellow,
        zl2: red,
        dp :additional,
        fge1:additional,
        fge2:additional,
        fs1 :additional,
        fs2 :additional,
        hf :additional,
        lm :additional,
        m1 :additional,
        mda :additional,
        mf :additional,
        mfa :additional,
        tdp :additional,
        u1 :additional
};